web_title = "Automation Practice - Ultimate QA"
Second_title = "Swag Labs"
Education = "xpath://a[text()='Education']"
Free_Courses= "xpath://li[contains(@class, 'menu-item')]/a[contains(text(), 'Free Courses')]"
Product= "class:collections__heading"
SignIn= "xpath=//a[contains(text(), 'Sign In')]"
SignIn_Text = "xpath://h2[@class='page__heading']"
Search_btn = "xpath: //div[@id='main-menu']//button"
Search_input = "xpath://input[contains(@class, 'et_pb_menu__search-input')]"
Search_input_placeholder = "Search …"
Search_input_title = "Search for:"
Filter_set = "class:product_sort_container"
btn_id= "id:add-to-cart-sauce-labs-bike-light"
add_cart= "xpath://button[contains(text(),'Add to cart')]"
invent_price= "xpath://div[@class='inventory_item_price']"
shop_cart_badge = "class:shopping_cart_badge"
shop_cart_cont = "id:shopping_cart_container"
invent_name= "xpath://div[@class='inventory_item_name']"
check_btn = "id:checkout"
first_txt = "id:first-name"
last_txt = "id:last-name"
postal_txt = "id:postal-code"
btn_continue = "id:continue"
txt_Item_total = "xpath://div[@class='summary_subtotal_label']"
txt_tax = "xpath://div[@class='summary_tax_label']"
txt_total = "xpath://div[@class='summary_total_label']"